export default {
  SET_SIDEBAR_ACTIVE_TAB: "CONFIG/SET_SIDEBAR_ACTIVE_TAB",
  SET_AUDIO: "CONFIG/SET_AUDIO",
  SET_INSPECTOR_VALUES: "INSPECTOR/SET_INSPECTOR_VALUES",
  SET_BRUSH_PROPERTIES: "DRAWING/SET_BRUSH_PROPERTIES",
};