export default [
  "Abril Fatface",
  "Alfa Slab One",
  "Amatic SC",
  "Anton",
  "Bangers",
  "Big Shoulders Display",
  "Bitter",
  "Bree Serif",
  "Carter One",
  "Catamaran",
  "Caveat",
  "Cinzel",
  "Comfortaa",
  "Cormorant Garamond",
  "Courgette",
  "Dancing Script",
  "Francois One",
  "IBM Plex Sans",
  "Inconsolata",
  "Indie Flower",
  "Josefin Sans",
  "Kanit",
  "Lato",
  "Lobster",
  "Lora",
  "Mansalva",
  "Martel",
  "Merriweather",
  "Noto Serif",
  "Oleo Script",
  "Open Sans",
  "Open Sans Condensed:300",
  "Oswald",
  "PT Serif",
  "Pacifico",
  "Patua One",
  "Permanent Marker",
  "Playball",
  "Playfair Display",
  "Raleway",
  "Ravi Prakash",
  "Reenie Beanie",
  "Righteous",
  "Roboto",
  "Roboto Condensed",
  "Roboto Mono",
  "Roboto Slab",
  "Sacramento",
  "Saira Stencil One",
  "Satisfy",
  "Shadows Into Light",
  "Slabo 27px",
  "Squada One",
  "Teko",
  "Vibes",
  "Volkhov",
  "Vollkorn SC",
  "Work Sans",
  "Yeseva One",
  "Zilla Slab"
];